function checkIss(t,e){for(i=0;i<t.length;i++)if(t[i]==e)return!0
return!1}function isrtl(t){var e=["Amiri-Regular","Amiri-Bold","Amiri-BoldSlanted","Amiri-Slanted","Arimo-Regular","Arimo-Bold","Arimo-BoldItalic","Arimo-Italic"]
return checkIss(e,t)}function split_file_menu(){$(".file-menu").each(function(){var t=$("tr",this).size(),e=$("tr td",this).size(),i=$("tr td",this).first().width()
if(14==e&&1==t&&45>i)$("tr:first",this).after("<tr></tr>"),$("tr:first td:gt(6)",this).detach().appendTo($("tr:nth-child(2)",this))
else if(14==e&&2==t&&i>90){var a=$("tr:nth-child(2)",this).html()
$("tr:nth-child(2)",this).remove(),$("tr:nth-child(1)",this).append(a)}if(12==e&&1==t&&45>i)$("tr:first",this).after("<tr></tr>"),$("tr:first td:gt(5)",this).detach().appendTo($("tr:nth-child(2)",this))
else if(12==e&&2==t&&i>90){var a=$("tr:nth-child(2)",this).html()
$("tr:nth-child(2)",this).remove(),$("tr:nth-child(1)",this).append(a)}if(10==e&&1==t&&45>i)$("tr:first",this).after("<tr></tr>"),$("tr:first td:gt(4)",this).detach().appendTo($("tr:nth-child(2)",this))
else if(10==e&&2==t&&i>90){var a=$("tr:nth-child(2)",this).html()
$("tr:nth-child(2)",this).remove(),$("tr:nth-child(1)",this).append(a)}})}function disable_frames(){var t=$("#dfrom").val(),e=$("#dto").val()
$("#animation-frames li").each(function(i,a){i+=1,i>=t&&e>=i&&($(this).fadeTo(100,.3),$(this).addClass("disabled"),$(this).children(".frame-tools").children(".frame-disabler").html("enable"),$(this).children(".filename-holder").prop("disabled",!0))})}function enable_frames(){var t=$("#dfrom").val(),e=$("#dto").val()
$("#animation-frames li").each(function(i,a){i+=1,i>=t&&e>=i&&($(this).fadeTo(100,1),$(this).removeClass("disabled"),$(this).children(".frame-tools").children(".frame-disabler").html("skip"),$(this).children(".filename-holder").prop("disabled",!1))})}$(function(t){function e(e,i,a){t('input[name="f'+e+"["+i+']"]').val(a)}t.ajaxSetup({cache:!1}),t(document).on("change","input.single",function(){1==t(this).is(":checked")&&t(this).parent().siblings().children("input.single").attr("checked",!1)}),t(document).on("submit",".ajax-form",function(e){e.preventDefault(),t(".ajax-form input:submit").attr("disabled",!0),t("#output").fadeTo(30,.45),t("#output").html('<img src="https://ezgif.com/images/loadcat.gif" class="loadcat" alt="Loading..." />'),t.ajax({type:"POST",url:t(this).attr("action")+"?ajax=true",data:t(this).serialize(),success:function(e){t("#output").html(e),t("#output").fadeTo(150,1),t(".ajax-form input:submit").attr("disabled",!1),split_file_menu()},error:function(e,i,a){t("#output").html("<p><b>Argh! You broke it...</b></p><p>Something went wrong while processing your request.<br />Maybe the file was too large and the operation timed out, or network crashed while waiting for the result.</p><p>Status code: "+e.status+"</p>"),t("#output").fadeTo(150,1),t(".ajax-form input:submit").attr("disabled",!1)}})}),t(".video-to-gif-tool").on("change",function(){"ffmpeg"==t(this).val()?t("#o-static").fadeIn(100):t("#o-static").hide()}),t(".toggle-sub-options").on("change",function(){1==t(this).is(":checked")?t(this).parent().next(".sub-options").fadeIn(100):t(this).parent().next(".sub-options").hide()}),t(document).on("keyup","#delay",function(){t(".frame-delay input").val(t(this).val())}),t(document).on("change","#gravity",function(){var e=t(this).val(),i=t(this).data("maxwidth"),a=t(this).data("maxheight")
t("#animation-frames li").each(function(n,l){var r=t(this).data("height"),o=t(this).data("width"),s=0,h=0
"top-middle"==e&&(s=Math.floor((i-o)/2)),"top-right"==e&&(s=i-o),"middle-left"==e&&(h=Math.floor((a-r)/2)),"center"==e&&(h=Math.floor((a-r)/2),s=Math.floor((i-o)/2)),"middle-right"==e&&(h=Math.floor((a-r)/2),s=i-o),"bottom-left"==e&&(h=a-r),"bottom-middle"==e&&(h=a-r,s=Math.floor((i-o)/2)),"bottom-right"==e&&(h=a-r,s=i-o),t(this).children(".frame-pos").children("label").children(".leftpos").val(s),t(this).children(".frame-pos").children("label").children(".toppos").val(h)})}),t(document).on("click",".frame-disabler",function(e){e.preventDefault()
var i=t(this).parent().parent()
i.hasClass("disabled")?(i.fadeTo(100,1),i.removeClass("disabled"),i.children(".frame-tools").children(".frame-disabler").html("skip"),i.children(".filename-holder").prop("disabled",!1),i.children(".frame-delay").children("label").children("input").prop("disabled",!1)):(i.fadeTo(100,.3),i.addClass("disabled"),i.children(".frame-tools").children(".frame-disabler").html("enable"),i.children(".filename-holder").prop("disabled",!0),i.children(".frame-delay").children("label").children("input").prop("disabled",!0))}),t(document).on("click",".frame-dupe",function(e){e.preventDefault()
var i=t(this).parent().parent()
i.clone(!0).insertAfter(t(this).parent().parent()).hide().toggle("clip")}),t(document).on("click",".form a.ignore",function(e){e.preventDefault(),t(this).parent().parent().remove()}),t("#animation-frames").sortable({handle:".imw"}),t("#overlay-image").draggable({cursor:"move",containment:"#overlay-container",scroll:!1,drag:function(){t("#posX").val(t("#overlay-image").css("left").replace("px","")),t("#posY").val(t("#overlay-image").css("top").replace("px",""))}}),t(".f-font").on("change",function(){isrtl(t(this).val())?t(this).parent().siblings("textarea.f-text").css("direction","rtl"):t(this).parent().siblings("textarea.f-text").css("direction","ltr")}),t(document).on("click",".add-frame-text",function(i){i.preventDefault()
var a=t(this).siblings(".f-num").val(),n=t(this).siblings(".f-text").val(),l=t(this).siblings(".txt-opt").children(".f-size").val(),r=t(this).siblings(".txt-opt").children(".f-font").val(),o=t(this).siblings(".txt-opt").children(".f-align").val(),s=t(this).siblings(".txt-opt").children(".f-color").val(),h=t(this).siblings(".txt-opt").children(".f-border").val(),d=t(this).siblings(".txt-opt").children(".f-op").val(),c=t(this).siblings(".f-left").val(),f=t(this).siblings(".f-top").val(),p=t(this).siblings(".f-dragged").val(),m=t('input[name="file"]').val(),u=t(this).parent().parent().parent().children(".i")
n.length>0?t.ajax({type:"POST",dataType:"json",url:t(".ajax-form").attr("action"),data:{fnum:a,text:n,size:l,font:r,align:o,color:s,border:h,op:d,left:c,top:f,dragged:p,file:m},success:function(i){u.html(i.image),e(a,"left",i.left),e(a,"top",i.top),e(a,"file",i.file),u.children("img").draggable({cursor:"move",containment:u,scroll:!1,stop:function(){e(a,"left",t(this).css("left").replace("px","")),e(a,"top",t(this).css("top").replace("px","")),e(a,"dragged",1)}})}}):(u.html(""),e(a,"left",0),e(a,"top",0),e(a,"dragged",0))}),t(document).on("change",".new-width",function(){var e=t("#old_width").val(),i=t("#width").val(),a=i/e*100
t("#percentage").val(a.toFixed(2))}),t(document).on("change",".new-height",function(){var e=t("#old_height").val(),i=t("#height").val(),a=i/e*100
t("#percentage").val(a.toFixed(2))}),t(document).on("change",".new-percentage",function(){var e=t("#old_width").val(),i=t("#percentage").val(),a=e/100*i
t("#width").val(a.toFixed()),t("#height").val("")}),split_file_menu()}),$(window).resize(function(){split_file_menu()})
